### ISSUE TITLE
number extractor fails for object with no cutouts

### ISSUE THREAD

**Issue by beckermr** [esheldon/meds#11]
It appears that the number extractor fails on objects with no cutouts when they are the only ones requested. The offending line is here

https://github.com/esheldon/meds/blob/master/meds/number_extractor.py#L75

This should probably return `[(-1,-1)]` instead of `-1,-1`. This bug looks like it is from me when I wrote this!

**Comment by esheldon** [comment]
yep

**Comment by beckermr** [comment]
Fixed with PR #18
