### ISSUE TITLE
roundoff error in bounds checking for coadds

### ISSUE THREAD

**Issue by beckermr** [esheldon/meds#20]
It appears that some coadd detections do not make it through this line https://github.com/esheldon/meds/blob/master/meds/maker.py#L406. This is the second bounds check from by converting ra,dec to row,col and then checking the image.

**Comment by esheldon** [comment]
This never happened in the old C++ maker, I thought we copied over that logic pretty much exactly

**Comment by beckermr** [comment]
We are using a different WCS library. Maybe difference might be in the inversion of the WCS?

**Comment by beckermr** [comment]
See PR #22 to fix this.
