### ISSUE TITLE
silent bug in extractor code?

### ISSUE THREAD

**Issue by beckermr** [esheldon/meds#3]
Are lines 136-138 of extractor.py correct? 

They currently read
```python
ncutout_last = data['ncutout'][ilast]
npix_last = data['box_size'][ilast]**2 * ncutout_last
cend     = data['start_row'][ilast,ncutout_last-1] + npix_last
```

This is weird since the number of pixels for the object is ```data['box_size'][ilast]**2 * ncutout``` but you add this length to the start of the last cutout for the object, ```data['start_row'][ilast,ncutout_last-1]```.

I think ```npix_last``` should just be ```data['box_size'][ilast]**2```.

**Comment by esheldon** [comment]
Yeah, I'm too many pixels.  As you say it is "silent" since they are just extra bytes at the end.

**Comment by beckermr** [comment]
I will push a fix.

**Comment by beckermr** [comment]
The bug fix for this issue has been pushed already.
